development:
  metareview_webservice_url: 'http://peerlogic.csc.ncsu.edu/metareview/metareviewgenerator/'
  reputation_web_service_url: 'http://peerlogic.csc.ncsu.edu/reputation/calculations/reputation_algorithms'
  summary_webservice_url: 'http://peerlogic.csc.ncsu.edu/sum/v1.0/summary/8/lsa'
  topic_bidding_webservice_url: 'http://peerlogic.csc.ncsu.edu/intelligent_assignment/merge_teams'
  heatmap_webservice_url: 'http://peerlogic.csc.ncsu.edu/reviewsentiment/configure'
  sentiment_webservice_url: 'http://peerlogic.csc.ncsu.edu/sentiment/'
  problem_webservice_url: 'http://peerlogic.csc.ncsu.edu/problem/'
  suggestions_webservice_url: 'http://peerlogic.csc.ncsu.edu/suggestions/'
  emotions_webservice_url: 'http://peerlogic.csc.ncsu.edu/emotions/'

test:
  metareview_webservice_url: 'http://peerlogic.csc.ncsu.edu/metareview/metareviewgenerator/'
  reputation_web_service_url: 'http://peerlogic.csc.ncsu.edu/reputation/calculations/reputation_algorithms'
  summary_webservice_url: 'http://peerlogic.csc.ncsu.edu/sum/v1.0/summary/8/lsa'
  topic_bidding_webservice_url: 'http://peerlogic.csc.ncsu.edu/intelligent_assignment/merge_teams'
  heatmap_webservice_url: 'http://peerlogic.csc.ncsu.edu/reviewsentiment/configure'
  sentiment_webservice_url: 'http://peerlogic.csc.ncsu.edu/sentiment/'
  problem_webservice_url: 'http://peerlogic.csc.ncsu.edu/problem/'
  suggestions_webservice_url: 'http://peerlogic.csc.ncsu.edu/suggestions/'
  emotions_webservice_url: 'http://peerlogic.csc.ncsu.edu/emotions/'

production:
  metareview_webservice_url: 'http://peerlogic.csc.ncsu.edu/metareview/metareviewgenerator/'
  reputation_web_service_url: 'http://peerlogic.csc.ncsu.edu/reputation/calculations/reputation_algorithms'
  summary_webservice_url: 'http://peerlogic.csc.ncsu.edu/sum/v1.0/summary/8/lsa'
  topic_bidding_webservice_url: 'http://peerlogic.csc.ncsu.edu/intelligent_assignment/merge_teams'
  heatmap_webservice_url: 'http://peerlogic.csc.ncsu.edu/reviewsentiment/configure'
  sentiment_webservice_url: 'http://peerlogic.csc.ncsu.edu/sentiment/'
  problem_webservice_url: 'http://peerlogic.csc.ncsu.edu/problem/'
  suggestions_webservice_url: 'http://peerlogic.csc.ncsu.edu/suggestions/'
  emotions_webservice_url: 'http://peerlogic.csc.ncsu.edu/emotions/'
